services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polling_stations_api
    ports:
      - "8080:8080"
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      - default

  postgres:
    image: postgres:latest
    container_name: polling_stations_db
    ports:
      - "5432:5432"
    restart: no
    healthcheck:
      test: "pg_isready -h postgres -U $$POSTGRES_USER -d polling_stations_db"
      interval: 10s
      timeout: 20s
      retries: 5
    volumes:
      - ./docker/storage/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polling_stations_db
      PG_TRUST_LOCALNET: true
      PGHOST: localhost
    networks:
      - default

networks:
  default:
    driver: bridge
