spring:
  application:
    name: polling_stations_api
  profiles:
    default: dev
  data:
    rest:
      base-path: /api
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  mustache:
    check-template-location: false
  flyway:
    enabled: true
